### ISSUE TITLE
Code-Review defects

### ISSUE THREAD

**Issue by mariuskueng** [livioso/turbo-octo-hipster#14]
## rSyncMeNow.rb
- Minor
  - [x] 29    Nach jedem Komma müsste ein Space sein.
  - [x] 30    Nach jedem Komma müsste ein Space sein.
  - [x] 8 Require require_relative nicht mehr verwendet.
  - [x] 43    Kein Then in Multiline if
  - [x] 49    Kein Then in Multiline if
  - [x] 60    Kein Then in Multiline if
  - [x] 49    If not => unless verwenden
- Medium
  - [ ] 54 Designentscheidung bez. VPN dokumentieren
- Major
  - [ ] 66 Errorhandling verbessern => Verbesserungspotential.
  - [ ] Use rsync gem
## settings-example.json
- Minor
  - [ ] Settingsfile Naming nicht eindeutig. => Umbennen
  - [x] Keine Kommentare in JSON.
- Medium
  - [x] Whitespaces sollten nicht manuell escaped werden müssen

**Comment by livioso** [comment]
Fixing it. Will commit the changes in a bit.

**Comment by livioso** [comment]
Fixed most of the issues in bb4c047b6fe29aafad4e0e2df1256d4812186e89. Works on my machine. Please deploy on your machines too. Such issue, much excite, wow. :shipit:

Edit:
:warning: Don't know if we can / should fix the remaining ones now so I'll set it to won't fix for now. :+1:
